version: '3'

services:
  mp_music:
    image: registry.ongtu.com/mp-music:latest
    container_name: mp_music
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CACHE_KEY=music_player_documents
      - REDIS_TTL=600
      - PRISMIC_API=https://musicplayer.prismic.io/api
      - PRISMIC_ACCESS_TOKEN=MC5Xb3J3OFNnQUFDY0FqNG1k.77-9TU5bLe-_ve-_ve-_vSECWxJFJe-_ve-_vVPvv73vv71HJHfvv70tcV7vv73vv73vv73vv73vv71p
    ports:
      - 8086:8080
    networks:
      - chatnet
    restart: unless-stopped
  mp-notify:
    image: registry.ongtu.com/mp-notify:latest
    container_name: mp_notify
    ports:
      - 8001:8000
    environment:
      - SOCKETCLUSTER_WORKERS=2
      - SOCKETCLUSTER_PORT=8000
    networks:
      - chatnet
    restart: unless-stopped
  mp-client:
    image: registry.ongtu.com/mp-client:latest
    environment:
      - PORT=8080
      - NODE_ENV=production
    ports:
      - 80:8080
    networks:
      - chatnet
    restart: unless-stopped
networks:
  chatnet:
    driver: bridge